version: "3.9"
services:
  vroxy: &vroxy
    image: vroxy
    environment:
      - VROXY_HOST=0.0.0.0
      - PORT=8008
      - VROXY_WHITELIST=/vroxy/config/vrchat-whitelist.txt
    build:
      context: .
      target: base
    ports:
      - "8008:8008"
    volumes:
      - .:/vroxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/healthz"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  vroxy_e2e:
    <<: *vroxy
    ports: []
    profiles:
      - donotstart
  vroxy_e2e_authz:
    <<: *vroxy
    ports: []
    healthcheck:
      test: ["CMD", "curl", "-f", "--header", "Authorization: Bearer abc", "http://localhost:8008/healthz"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - VROXY_HOST=0.0.0.0
      - PORT=8008
      - VROXY_WHITELIST=/vroxy/config/vrchat-whitelist.txt
      - VROXY_AUTH_TOKENS=abc,123
    profiles:
      - donotstart
  vroxy-install-e2e.test:
    image: ${E2E_OS:-debian:bullseye}
    command: tail -F /dev/null
    environment:
      - CI=true
      - DEBIAN_FRONTEND=noninteractive
      - domain=vroxy-install-e2e.test
      - acme_server=https://pebble:14000/dir
    working_dir: /vroxy
    volumes:
      - .:/vroxy
    profiles:
      - donotstart
  pebble:
    image: letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver 10.30.50.3:8053
    # ports:
    #   - 14000:14000  # HTTPS ACME API
    #   - 15000:15000  # HTTPS Management API
    environment:
      - PEBBLE_VA_ALWAYS_VALID=1
    profiles:
      - vroxy_install
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "--no-check-certificate", "https://localhost:14000/dir"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/vroxy
    profiles:
      - donotstart
