services:
  vroxy: &vroxy
    image: vroxy
    environment:
      - VROXY_HOST=0.0.0.0
      - PORT=8008
      - VROXY_WHITELIST=/vroxy/config/vrchat-whitelist.txt
    build:
      context: .
      target: base
    ports:
      - "8008:8008"
    volumes:
      - .:/vroxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/healthz"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
  vroxy_e2e:
    <<: *vroxy
    ports: []
    profiles:
      - donotstart
  vroxy_e2e_authz:
    <<: *vroxy
    ports: []
    healthcheck:
      test: ["CMD", "curl", "-f", "--header", "Authorization: Bearer abc", "http://localhost:8008/healthz"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - VROXY_HOST=0.0.0.0
      - PORT=8008
      - VROXY_WHITELIST=/vroxy/config/vrchat-whitelist.txt
      - VROXY_AUTH_TOKENS=abc,123
    profiles:
      - donotstart
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/vroxy
    profiles:
      - donotstart
