name: CI

on:
  push:
    branches: [ "master" ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          make
      - name: run unit tests
        run: |
          make test
      - name: upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov/
      - name: run e2e tests
        run: |
          make test-e2e